import express from "express";
import dotenv from "dotenv";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer as createViteServer } from "vite";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, "..");
const isProduction = process.env.NODE_ENV === "production";
const port = Number(process.env.PORT || 5173);
const MODEL = process.env.ANTHROPIC_MODEL || "claude-haiku-4-5-20251001";
const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION = "2023-06-01";

loadEnvironment();

const app = express();
app.use(express.json({ limit: "4mb" }));

app.get("/api/health", (_req, res) => {
  res.json({
    ok: true,
    provider: "Claude",
    configured: Boolean(process.env.ANTHROPIC_API_KEY),
    model: MODEL,
  });
});

app.post("/api/chat", async (req, res) => {
  try {
    const payload = normalizeChatPayload(req.body);
    const citations = buildCitations(payload.question, payload.selectedSources);
    const system = buildNotebookSystemPrompt(payload, citations);
    const messages = [
      ...payload.history.slice(-8),
      { role: "user", content: payload.question },
    ];

    const response = await callClaude({
      system,
      messages,
      maxTokens: payload.answerStyle === "Detailed" ? 1800 : 1300,
    });

    res.json({
      content: response.text,
      citations,
      provider: "Claude",
      model: MODEL,
      usage: response.usage,
    });
  } catch (error) {
    sendApiError(res, error);
  }
});

app.post("/api/artifact", async (req, res) => {
  try {
    const payload = normalizeArtifactPayload(req.body);
    const system = buildArtifactSystemPrompt(payload);
    const response = await callClaude({
      system,
      messages: [
        {
          role: "user",
          content: `Create a ${payload.kind} artifact for this notebook using the selected sources.`,
        },
      ],
      maxTokens: payload.kind === "report" ? 2200 : 1600,
    });

    res.json({
      title: payload.title,
      subtitle:
        payload.selectedSources.length > 0
          ? `Generated by Claude from ${payload.selectedSources.length} selected source${payload.selectedSources.length === 1 ? "" : "s"}`
          : "Generated by Claude without selected sources",
      body: response.text,
      provider: "Claude",
      model: MODEL,
      usage: response.usage,
    });
  } catch (error) {
    sendApiError(res, error);
  }
});

app.post("/api/discover", async (req, res) => {
  try {
    const topic = String(req.body?.topic || "").trim().slice(0, 160);
    if (!topic) {
      return res.status(400).json({ error: "Topic is required." });
    }

    const response = await callClaude({
      system:
        "You generate concise research starter sources for a NotebookLM-style workspace. Return tool input only.",
      messages: [
        {
          role: "user",
          content: `Create three useful source documents for researching: ${topic}`,
        },
      ],
      maxTokens: 1800,
      tools: [
        {
          name: "return_sources",
          description: "Return generated research starter sources.",
          input_schema: {
            type: "object",
            additionalProperties: false,
            required: ["sources"],
            properties: {
              sources: {
                type: "array",
                minItems: 3,
                maxItems: 3,
                items: {
                  type: "object",
                  additionalProperties: false,
                  required: ["title", "kind", "body"],
                  properties: {
                    title: { type: "string" },
                    kind: {
                      type: "string",
                      enum: ["doc", "url", "text", "slide", "ebook"],
                    },
                    body: { type: "string" },
                  },
                },
              },
            },
          },
        },
      ],
      toolChoice: { type: "tool", name: "return_sources" },
    });

    res.json({
      sources: sanitizeDiscoveredSources(response.toolInput?.sources),
      provider: "Claude",
      model: MODEL,
      usage: response.usage,
    });
  } catch (error) {
    sendApiError(res, error);
  }
});

if (isProduction) {
  app.use(express.static(join(root, "dist")));
  app.get(/.*/, (_req, res) => {
    res.sendFile(join(root, "dist", "index.html"));
  });
} else {
  const vite = await createViteServer({
    root,
    server: { middlewareMode: true },
    appType: "spa",
  });
  app.use(vite.middlewares);
}

app.listen(port, "127.0.0.1", () => {
  const llmState = process.env.ANTHROPIC_API_KEY ? "Claude configured" : "Claude key missing";
  console.log(`NotebookLM clone running at http://127.0.0.1:${port}/ (${llmState})`);
});

function loadEnvironment() {
  const envPaths = [
    join(root, ".env.local"),
    join(root, ".env"),
    ...String(process.env.BLOCKRESEARCH_ENV_PATHS || "")
      .split(":")
      .map((path) => path.trim())
      .filter(Boolean),
  ];

  for (const path of envPaths) {
    if (existsSync(path)) {
      dotenv.config({ path, override: false, quiet: true });
    }
  }
}

function normalizeChatPayload(body) {
  const question = String(body?.question || "").trim();
  if (!question || question.length > 4000) {
    throw statusError(400, "Question must be 1-4000 characters.");
  }

  const selectedSources = normalizeSources(body?.selectedSources);
  if (!selectedSources.length) {
    throw statusError(400, "Select at least one source before asking Claude.");
  }

  return {
    question,
    selectedSources,
    chatGoal: String(body?.chatGoal || "").slice(0, 800),
    chatPersona: String(body?.chatPersona || "Research analyst").slice(0, 80),
    answerStyle: String(body?.answerStyle || "Balanced").slice(0, 40),
    history: normalizeHistory(body?.history),
  };
}

function normalizeArtifactPayload(body) {
  const kind = String(body?.kind || "report");
  const allowedKinds = new Set([
    "audio",
    "video",
    "mindmap",
    "report",
    "flashcards",
    "quiz",
    "infographic",
  ]);
  if (!allowedKinds.has(kind)) {
    throw statusError(400, "Unsupported artifact kind.");
  }

  return {
    kind,
    title: String(body?.title || `${kind} artifact`).slice(0, 120),
    selectedSources: normalizeSources(body?.selectedSources),
    notes: Array.isArray(body?.notes)
      ? body.notes.slice(0, 8).map((note) => ({
          title: String(note?.title || "Note").slice(0, 100),
          body: String(note?.body || "").slice(0, 1200),
        }))
      : [],
  };
}

function normalizeSources(rawSources) {
  if (!Array.isArray(rawSources)) return [];
  return rawSources.slice(0, 30).map((source, index) => ({
    id: String(source?.id || `source-${index}`).slice(0, 100),
    title: String(source?.title || `Source ${index + 1}`).slice(0, 180),
    kind: String(source?.kind || "doc").slice(0, 30),
    body: String(source?.body || "").slice(0, 20000),
  })).filter((source) => source.body.trim());
}

function normalizeHistory(rawHistory) {
  if (!Array.isArray(rawHistory)) return [];
  return rawHistory
    .slice(-10)
    .map((message) => ({
      role: message?.role === "assistant" ? "assistant" : "user",
      content: String(message?.content || "").slice(0, 2500),
    }))
    .filter((message) => message.content.trim());
}

function buildNotebookSystemPrompt(payload, citations) {
  const sourceText = payload.selectedSources
    .map((source, index) => {
      return `<source index="${index + 1}" id="${escapeXml(source.id)}" title="${escapeXml(source.title)}" type="${escapeXml(source.kind)}">\n${source.body}\n</source>`;
    })
    .join("\n\n");
  const citationText = citations
    .map((citation) => `[${citation.index}] ${citation.sourceTitle}: ${citation.quote}`)
    .join("\n");

  return `You are a NotebookLM-style research assistant running inside a local clone.

Behavior rules:
- Answer only from the selected sources and the conversation context.
- If the selected sources do not support an answer, say exactly what is missing.
- Cite claims with bracket citations such as [1] using the citation snippets.
- Keep the answer useful, specific, and grounded. Do not mention hidden implementation details.
- Follow the user's configured role, response style, and goal.

Configured role: ${payload.chatPersona}
Configured response style: ${payload.answerStyle}
Configured goal: ${payload.chatGoal || "Help the user understand the selected sources."}

Citation snippets:
${citationText || "No snippets were pre-ranked. Cite source titles directly when needed."}

Selected sources:
${sourceText}`;
}

function buildArtifactSystemPrompt(payload) {
  const sourceText = payload.selectedSources
    .map((source, index) => `## Source ${index + 1}: ${source.title}\n${source.body}`)
    .join("\n\n---\n\n");
  const noteText = payload.notes.length
    ? payload.notes.map((note) => `- ${note.title}: ${note.body}`).join("\n")
    : "No saved notes.";

  return `You generate NotebookLM Studio outputs.

Output rules:
- Return only the finished artifact body in markdown.
- Ground the artifact in the selected sources.
- Be concrete and useful. Do not invent unsupported facts.
- For audio, write a host-ready script with sections and timing cues.
- For video, write a scene-by-scene narrated storyboard.
- For mindmap, write a compact hierarchy with relationships.
- For report, write a structured briefing.
- For flashcards, write front/back cards.
- For quiz, write questions, options, answers, and explanations.
- For infographic, write panel copy and layout labels.

Requested artifact kind: ${payload.kind}
Saved notes:
${noteText}

Selected sources:
${sourceText || "No selected sources. Produce a minimal template and state that sources are missing."}`;
}

async function callClaude({ system, messages, maxTokens, tools, toolChoice }) {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw statusError(503, "ANTHROPIC_API_KEY is not configured.");
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 45000);
  try {
    const body = {
      model: MODEL,
      max_tokens: maxTokens,
      system,
      messages,
    };
    if (tools) body.tools = tools;
    if (toolChoice) body.tool_choice = toolChoice;

    const response = await fetch(ANTHROPIC_URL, {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": ANTHROPIC_VERSION,
        "content-type": "application/json",
      },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw statusError(
        response.status,
        data?.error?.message || `Claude API returned ${response.status}.`,
      );
    }

    const text = Array.isArray(data.content)
      ? data.content
          .filter((block) => block?.type === "text")
          .map((block) => block.text)
          .join("\n")
          .trim()
      : "";
    const toolUse = Array.isArray(data.content)
      ? data.content.find((block) => block?.type === "tool_use")
      : null;

    return {
      text: text || "Claude returned an empty response.",
      toolInput: toolUse?.input,
      usage: data.usage || null,
    };
  } finally {
    clearTimeout(timeout);
  }
}

function buildCitations(question, sources) {
  const terms = tokenize(question);
  const snippets = sources.flatMap((source) =>
    splitChunks(source.body).map((text) => ({
      source,
      text,
      score: scoreChunk(`${source.title} ${text}`, terms),
    })),
  );
  const ranked = snippets
    .filter((snippet) => snippet.score > 0)
    .sort((a, b) => b.score - a.score || b.text.length - a.text.length);
  const chosen = (ranked.length ? ranked : snippets).slice(0, 5);

  return chosen.map((snippet, index) => ({
    index: index + 1,
    sourceId: snippet.source.id,
    sourceTitle: snippet.source.title,
    quote: truncate(snippet.text, 220),
  }));
}

function tokenize(input) {
  const stop = new Set(["the", "and", "for", "from", "with", "that", "this", "what", "where", "when", "how", "are", "you", "your", "about"]);
  return String(input)
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .map((token) => token.trim())
    .filter((token) => token.length > 2 && !stop.has(token));
}

function scoreChunk(text, terms) {
  const tokens = tokenize(text);
  return terms.reduce((sum, term) => sum + tokens.filter((token) => token === term || token.includes(term)).length, 0);
}

function splitChunks(body) {
  return String(body)
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .flatMap((paragraph) => {
      if (paragraph.length <= 700) return [paragraph];
      return paragraph.match(/.{1,700}(\s|$)/g)?.map((part) => part.trim()).filter(Boolean) || [paragraph];
    });
}

function sanitizeDiscoveredSources(sources) {
  if (!Array.isArray(sources)) return [];
  return sources.slice(0, 3).map((source, index) => ({
    title: String(source?.title || `Discovered source ${index + 1}`).slice(0, 120),
    kind: ["doc", "url", "text", "slide", "ebook"].includes(source?.kind) ? source.kind : "doc",
    body: String(source?.body || "").slice(0, 6000),
  })).filter((source) => source.body.trim());
}

function sendApiError(res, error) {
  const status = Number(error?.status || 500);
  const safeStatus = status >= 400 && status < 600 ? status : 500;
  res.status(safeStatus).json({
    error: safeStatus === 500 ? "LLM request failed." : error.message,
  });
}

function statusError(status, message) {
  const error = new Error(message);
  error.status = status;
  return error;
}

function escapeXml(input) {
  return String(input)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function truncate(input, maxLength) {
  const clean = String(input).replace(/\s+/g, " ").trim();
  return clean.length > maxLength ? `${clean.slice(0, maxLength - 1).trim()}...` : clean;
}
